package com.media.smartcore.entity;
// Generated Aug 25, 2017 3:08:59 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * ScRole generated by hbm2java
 */
@Entity
@Table(name = "SC_ROLE")
public class ScRole extends BaseEntity implements java.io.Serializable {

	private String name;
	private String creatorId;
	private Date createDate;
	private String description;
	private Long defaultRole;

	public ScRole() {
	}

	public ScRole(String id) {
		this.id = id;
	}

	public ScRole(String id, String name, String creatorId, Date createDate, String description,
			Long defaultRole) {
		this.id = id;
		this.name = name;
		this.creatorId = creatorId;
		this.createDate = createDate;
		this.description = description;
		this.defaultRole = defaultRole;
	}

	@Id
	@GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid")
    @Column(columnDefinition = "CHAR(32)")
	public String getId() {
		return this.id;
	}


	@Column(name = "NAME", length = 512)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CREATOR_ID", length = 64)
	public String getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "DESCRIPTION", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "DEFAULT_ROLE", precision = 22, scale = 0)
	public Long getDefaultRole() {
		return this.defaultRole;
	}

	public void setDefaultRole(Long defaultRole) {
		this.defaultRole = defaultRole;
	}

}
