package com.media.smartcore.entity;
// Generated Aug 25, 2017 3:08:59 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * ScPermission generated by hbm2java
 */
@Entity
@Table(name = "SC_PERMISSION")
public class ScPermission extends BaseEntity implements java.io.Serializable {

	private String scUserId;
	private String scRightId;
	private String scResourceId;
	private String scUnitId;
	private String creatorId;
	private Date createDate;

	public ScPermission() {
	}

	public ScPermission(String id) {
		this.id = id;
	}

	public ScPermission(String id, String scUserId, String scRightId, String scResourceId, String scUnitId,
			String creatorId, Date createDate) {
		this.id = id;
		this.scUserId = scUserId;
		this.scRightId = scRightId;
		this.scResourceId = scResourceId;
		this.scUnitId = scUnitId;
		this.creatorId = creatorId;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid")
    @Column(columnDefinition = "CHAR(32)")
	public String getId() {
		return this.id;
	}

	@Column(name = "SC_USER_ID", length = 64)
	public String getScUserId() {
		return this.scUserId;
	}

	public void setScUserId(String scUserId) {
		this.scUserId = scUserId;
	}

	@Column(name = "SC_RIGHT_ID", length = 64)
	public String getScRightId() {
		return this.scRightId;
	}

	public void setScRightId(String scRightId) {
		this.scRightId = scRightId;
	}

	@Column(name = "SC_RESOURCE_ID", length = 64)
	public String getScResourceId() {
		return this.scResourceId;
	}

	public void setScResourceId(String scResourceId) {
		this.scResourceId = scResourceId;
	}

	@Column(name = "SC_UNIT_ID", length = 64)
	public String getScUnitId() {
		return this.scUnitId;
	}

	public void setScUnitId(String scUnitId) {
		this.scUnitId = scUnitId;
	}

	@Column(name = "CREATOR_ID", length = 64)
	public String getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
