package com.media.smartcore.entity;
// Generated Aug 25, 2017 3:08:59 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * ScRoleGroup generated by hbm2java
 */
@Entity
@Table(name = "SC_ROLE_GROUP")
public class ScRoleGroup extends BaseEntity implements java.io.Serializable {

	private String scRoleId;
	private String name;
	private String creatorId;
	private Date createDate;
	private String description;

	public ScRoleGroup() {
	}

	public ScRoleGroup(String id) {
		this.id = id;
	}

	public ScRoleGroup(String id, String scRoleId, String name, String creatorId, Date createDate,
			String description) {
		this.id = id;
		this.scRoleId = scRoleId;
		this.name = name;
		this.creatorId = creatorId;
		this.createDate = createDate;
		this.description = description;
	}

	@Id
	@GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid")
    @Column(columnDefinition = "CHAR(32)")
	public String getId() {
		return this.id;
	}

	@Column(name = "SC_ROLE_ID", length = 64)
	public String getScRoleId() {
		return this.scRoleId;
	}

	public void setScRoleId(String scRoleId) {
		this.scRoleId = scRoleId;
	}

	@Column(name = "NAME", length = 512)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CREATOR_ID", length = 64)
	public String getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "DESCRIPTION", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
